<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="111" started-at="2020-12-01T19:02:27 CST" finished-at="2020-12-01T19:02:27 CST">
    <groups>
      <group name="re testing">
        <method signature="Groupsdemo.testcase5()[pri:0, instance:com.testng.Groupsdemo@1f554b06]" name="testcase5" class="com.testng.Groupsdemo"/>
      </group> <!-- re testing -->
      <group name="regression testing">
        <method signature="Groupsdemo.testcase4()[pri:0, instance:com.testng.Groupsdemo@1f554b06]" name="testcase4" class="com.testng.Groupsdemo"/>
      </group> <!-- regression testing -->
      <group name="smoketesting">
        <method signature="Groupsdemo.testcase4()[pri:0, instance:com.testng.Groupsdemo@1f554b06]" name="testcase4" class="com.testng.Groupsdemo"/>
        <method signature="Groupsdemo.testcase5()[pri:0, instance:com.testng.Groupsdemo@1f554b06]" name="testcase5" class="com.testng.Groupsdemo"/>
      </group> <!-- smoketesting -->
    </groups>
    <test name="Test" duration-ms="111" started-at="2020-12-01T19:02:27 CST" finished-at="2020-12-01T19:02:27 CST">
      <class name="com.testng.Groupsdemo">
        <test-method status="PASS" signature="testcase4()[pri:0, instance:com.testng.Groupsdemo@1f554b06]" name="testcase4" duration-ms="10" started-at="2020-12-01T19:02:27 CST" finished-at="2020-12-01T19:02:27 CST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase4 -->
        <test-method status="FAIL" signature="testcase5()[pri:0, instance:com.testng.Groupsdemo@1f554b06]" name="testcase5" duration-ms="5" started-at="2020-12-01T19:02:27 CST" finished-at="2020-12-01T19:02:27 CST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.testng.Groupsdemo.testcase5(Groupsdemo.java:14)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase5 -->
      </class> <!-- com.testng.Groupsdemo -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
